name: Say Hello
on: [push]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Hello world action steps
        id: greet
        uses: ./
        with:
          who-to-greet: Samsam
      - name: Get the output time
        run: echo "The time was ${{ steps.greet.outputs.time}}"
